language: ruby
sudo: false
script: bundle exec rake dev:spec_with_app_load
rvm:
  - 2.5.1
cache:
  bundler: true
  directories:
    - ./tmp/solr_dist
    # cache phantomjs auto-installed by jasmine and phantomjs gem, speed
    # things up a bit.
    - $HOME/.phantomjs
before_script:
  - jdk_switcher use oraclejdk8
  - psql -c 'create database scihist_sufia_test;' -U postgres
  -
# We need redis even in test due to sufia/curation_concerns
# use of redlock gem in some internals.
services:
  - redis-server
  - postgresql

env:
  matrix:
  - secure: P/iCE9cJn62iR9zHzHpCnT9a5cizKS7ASBxs7vM2OPKkc335Dxm4VxzejEFmVOqWAT//utGzLI6MGLYkqFwYIZznB6oJucEIz5Xp+ABOX6ZWMN3bueU2BILiRW9AVWWZVH+19KXSOQVqh1dz55Cv8J8iwUHfXdZCmdOoli5TzAI=
  - secure: m7YZobFsjitZ5PLKKWEYEopNBRku5ot8St4HA3o2/t/PEgQrep74/+01Styl5RHb8ZAbFCM6hgt4asQczsujEF86+65NW3AKEpjcgL4zQ1+98Dd3+qApwh5JGgiwu2u31noQ6x/PfLO4k6E0vMtshfni91WDGPXsLZRP/3hzPns=