language: ruby
sudo: false
script: bundle exec rake dev:spec_with_app_load
rvm:
  - 2.5.1
cache:
  bundler: true
  directories:
    - ./tmp/solr_dist
    # cache phantomjs auto-installed by jasmine and phantomjs gem, speed
    # things up a bit.
    - $HOME/.phantomjs
before_script:
  - jdk_switcher use oraclejdk8
  - psql -c 'create database scihist_sufia_test;' -U postgres
  -
# We need redis even in test due to sufia/curation_concerns
# use of redlock gem in some internals.
services:
  - redis-server
  - postgresql

env:
  global:
  - secure: Nom1EhdruXCCqnP2TncEJnq/iVfF9vMTIdtwgi+9MqEJVNM+yFcZ+gmU4GbVLwIaW06L+AjSDKgf6NbZMhkf05aJLEGSFwCRK8KQy0ZGrzAM/KuhirNQP5HSnX15XL3hmZwIPmBq7DoF1o6LgyyQ5Xey+JbepTZt/WMk3wo0VD4=
  - secure: P0g6AmpNHLG/l57KzgHBjCMRiqk45T1bC4HRTxcwuRnZn1EiniEjp7ratFyb9LqxLkM+RkbB31YHWdmiYT16HyNNoTLA9r7B7oXh9fIi++2pqg7wEK8aBB286Zj/4b5lQxQPxMVhbkUtEY1ocw56SpU1YJOHPVkb+/8FCdturwc=
