language: ruby
sudo: false
script: bundle exec rake dev:spec_with_app_load
rvm:
  - 2.3.1
cache:
  bundler: true
  directories:
    - ./tmp/solr_dist
before_script:
  - jdk_switcher use oraclejdk8
# We need redis even in test due to sufia/curation_concerns
# use of redlock gem in some internals.
services:
  - redis-server
