# This is a bit non-standard, see https://github.com/chemheritage/chf-sufia/issues/234#issuecomment-291967455
terms:
  - id: Image
    term: Image
    uri: http://purl.org/dc/dcmitype/StillImage
  - id: Mixed Material
    term: Mixed Material
    uri: http://id.loc.gov/vocabulary/resourceTypes/mix
  - id: Moving Image
    term: Moving Image
    uri: http://purl.org/dc/dcmitype/MovingImage
  - id: Physical Object
    term: Physical Object
    uri: http://purl.org/dc/dcmitype/PhysicalObject
  - id: Sound
    term: Sound
    uri: http://purl.org/dc/dcmitype/Sound
  - id: Text
    term: Text
    uri: http://purl.org/dc/dcmitype/Text
