terms:
  - id: http://purl.org/dc/dcmitype/MovingImage
    term: Moving Image
  - id: http://purl.org/dc/dcmitype/StillImage
    term: Image
  - id: http://id.loc.gov/vocabulary/resourceTypes/mix
    term: Mixed Material
  - id: http://purl.org/dc/dcmitype/PhysicalObject
    term: Physical Object
  - id: http://purl.org/dc/dcmitype/Sound
    term: Sound
  - id: http://purl.org/dc/dcmitype/Text
    term: Text
