# This is a sample config file that points to a solr server for each environment
development:
  url: http://localhost:8080/hydra/collection1
test:
  url: http://localhost:8080/hydra/test
production:
  url: http://your.production.server:8080/bl_solr/core0
