#config/solr_wrapper_test.yml
# version: 6.0.0
port: 8985
instance_dir: tmp/solr-test
  <% # in subdir of tmp to make it easier to tell travis to cache,
     # so we're not downloading it over and over. Make sure it exists.
     FileUtils.mkdir_p("tmp/solr_dist") %>
download_dir: "tmp/solr_dist"
collection:
    persist: false
    dir: solr/config
    name: hydra-test
version: 6.3.0

# To simply ignore the checksum, you can set validate to false.
# The default is true; we are currently downloading the checksum.
# validate: false

# Attempt to use mirror url to keep travis tests from being blocked by
# apache for too many solr downloads.
mirror_url: http://lib-solr-mirror.princeton.edu/dist/
