#config/solr_wrapper_test.yml
# version: 6.0.0
port: 8985
instance_dir: tmp/solr-test
  <% # in subdir of tmp to make it easier to tell travis to cache,
     # so we're not downloading it over and over. Make sure it exists.
     FileUtils.mkdir_p("tmp/solr_dist") %>
download_dir: "tmp/solr_dist"
collection:
    persist: false
    dir: solr/config
    name: hydra-test
version: 6.3.0


# Attempt to use mirror url to keep travis tests from being blocked by
# apache for too many solr downloads.
# (Commenting this out, as it was more trouble than it was worth. See
# https://github.com/sciencehistory/chf-sufia/pull/1153
# for more details.)
# mirror_url: http://lib-solr-mirror.princeton.edu/dist/

url: https://s3.amazonaws.com/science-history-build-cache/solr/6.3.0/solr-6.3.0.zip
validate: false