#config/solr_wrapper_test.yml
# version: 6.0.0
port: 8985
instance_dir: tmp/solr-test
  <% # in subdir of tmp to make it easier to tell travis to cache,
     # so we're not downloading it over and over. Make sure it exists.
     FileUtils.mkdir_p("tmp/solr_dist") %>
download_dir: "tmp/solr_dist"
collection:
    persist: false
    dir: solr/config
    name: hydra-test
version: 6.3.0


# This signed URL makes use of two env variables defined in .travis.yml:
# - AWS_ACCESS_KEY_ID_FOR_SOLR=[secure]
# - AWS_SECRET_ACCESS_KEY_FOR_SOLR=[secure]
# Since we're downloading directly from our own S3 bucket, no need to validate:
validate: false

<% require 'aws-sdk-s3'
  s3 = Aws::S3::Client.new( region: 'us-east-1', access_key_id:  ENV['AWS_ACCESS_KEY_ID_FOR_SOLR'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY_FOR_SOLR'] )
  signer = Aws::S3::Presigner.new(client: s3) %>
url: '<%= signer.presigned_url( :get_object, bucket: 'science-history-build-cache', key: "solr-6.3.0.tgz" ) %>'

solr_zip_path: 'tmp/solr-6.3.0.zip'