#config/solr_wrapper_test.yml
# version: 6.0.0
port: 8985
instance_dir: tmp/solr-test
  <% # in subdir of tmp to make it easier to tell travis to cache,
     # so we're not downloading it over and over. Make sure it exists.
     FileUtils.mkdir_p("tmp/solr_dist") %>
download_dir: "tmp/solr_dist"
collection:
    persist: false
    dir: solr/config
    name: hydra-test
version: 6.3.0


# Use mirror url to keep travis tests from being blocked by
# apache for too many solr downloads.
# Ignore the checksum, which is coming from apache until
# https://github.com/cbeer/solr_wrapper/pull/119 is merged.

mirror_url: http://lib-solr-mirror.princeton.edu/dist/
validate: false

# See also:
# https://github.com/cbeer/solr_wrapper/issues/122
# https://github.com/sciencehistory/chf-sufia/pull/1153